### ISSUE TITLE
Quantifiers generate TypeError

### ISSUE THREAD

**Issue by mavbig** [asciimoo/exrex#22]
Hi!

I tried to generate passwords using patterns, like 2 upper case letters and 2 lower case letters need to be in the generated string, but I ran into the following problem. For example this regex:

`^(?=(.*[A-Z])){2}(?=(.*[a-z])){2}(?=.*\d)(?=.*[\!\_\"])[A-Za-z\d\!\_\"]{9,9}$`

As you can see I have two {2} selectors in the regex, and this throws the following error:
```Traceback (most recent call last):
  File "regexpassgen.py", line 17, in <module>
    for p in passwords:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 134, in prods
    for i in ret:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 143, in ggen
    for a in g1:
  File "/usr/local/lib/python2.7/dist-packages/exrex.py", line 148, in ggen
    yield a + b
TypeError: can only concatenate list (not "unicode") to list
```
I think the curly brackets need to be escaped or something? I'm not quite sure, but without them the command parameter runs just fine. Can you think of a hint how to fix it?

**Comment by asciimoo** [comment]
@mavbig hopefully it is fixed. Could you confirm?

**Comment by mavbig** [comment]
Unfortunately still the same error message, I used this python script to execute my command [https://gist.github.com/johngian/9005563](url)

```
root@kali:~/Desktop# python regexpassgen.py '^(?=(.*[A-Z])){2}(?=(.*[a-z])){2}(?=.*\d)(?=.*[\!\_\"])[A-Za-z\d\!\_\"]{9,9}$'
Traceback (most recent call last):
  File "regexpassgen.py", line 17, in <module>
    for p in passwords:
  File "/root/Desktop/exrex.py", line 134, in prods
    for i in ret:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 143, in ggen
    for a in g1:
  File "/root/Desktop/exrex.py", line 148, in ggen
    yield a + b
TypeError: can only concatenate list (not "unicode") to list
```
I'm not quite sure if this should even work, but thanks for your help anyway!

**Comment by asciimoo** [comment]
@mavbig it works for me with the latest exrex:

```
$ python exrex.py '^(?=(.*[A-Z])){2}(?=(.*[a-z])){2}(?=.*\d)(?=.*[\!\_\"])[A-Za-z\d\!\_\"]{9,9}$' | head    1 ↵
AAaa0!AAAAAAAAA
AAaa0!AAAAAAAAB
AAaa0!AAAAAAAAC
AAaa0!AAAAAAAAD
AAaa0!AAAAAAAAE
AAaa0!AAAAAAAAF
AAaa0!AAAAAAAAG
AAaa0!AAAAAAAAH
AAaa0!AAAAAAAAI
AAaa0!AAAAAAAAJ
[...]
```

**Comment by mavbig** [comment]
Oh yes it does, so the error was in the python script which called your function. Well that's awesome, thanks for your fast help!

Have a nice day!
